# Generated by Django 5.1.7 on 2025-03-24 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
                'indexes': [models.Index(fields=['name'], name='departments_name_c59a45_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'positions',
                'indexes': [models.Index(fields=['title'], name='positions_title_94e831_idx')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_department', to='master_config.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_position', to='master_config.position')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['-date_of_joining'],
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='employees_first_n_235346_idx'), models.Index(fields=['email'], name='employees_email_f66e96_idx'), models.Index(fields=['phone_number'], name='employees_phone_n_2d3781_idx'), models.Index(fields=['date_of_joining'], name='employees_date_of_e463b2_idx'), models.Index(fields=['department'], name='employees_departm_24ab5f_idx'), models.Index(fields=['position'], name='employees_positio_2577e6_idx')],
            },
        ),
    ]
